### ISSUE TITLE
Bug z wygenerowaniem wniosku

### ISSUE THREAD

**Issue by Helga151** [akai-org/AKAI-generator-wnioskow-symfony#32]
![obraz](https://user-images.githubusercontent.com/82333349/155884019-59b09100-f8bc-4699-bcff-3dfd18cc446d.png)
![obraz](https://user-images.githubusercontent.com/82333349/155883964-117b4574-b0dc-41b0-804a-2c45bfc0efc0.png)
Dane:
Olga Gerlich
członek zespołu Joystick - programista Vue.js
zimowy
Projekt Joystick
Uczestnictwo w spotkaniach AKAI

**Comment by roertbb** [comment]
Prawdopodobnie `.` w polu `Funkcja` jest problemem

**Comment by mozzar** [comment]
blad wynikal z walidacji i blednymi datatypami closed.
